use socketchat ; 

CREATE TABLE IF NOT EXISTS lastlogin ( `user` VARCHAR(20) NOT NULL , `time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`user`)) ENGINE = InnoDB; 

CREATE TABLE IF NOT EXISTS messages ( `id` INT NOT NULL AUTO_INCREMENT , `user` VARCHAR(20) NOT NULL , `belongsto` VARCHAR(20) NOT NULL , `message` VARCHAR(255) NOT NULL , `time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB; 